# import path to your theme
import = 

[font]
size = 12

[font.bold]
family = "Fira Code"
style = "Medium"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 1
y = 1

[window]
opacity = 0.90

[window.padding]
x = 30
y = 30
