require("packer.packer")
require("packer.telescope")
require("packer.tree")
require("packer.treesitter")
require("packer.lsp")
require("packer.catppuccin")
require("packer.copilot")
require("packer.lsp")
require("packer.cmp")
require("packer.bufferline")
require("packer.spectre")
require("packer.nvterm")
require("packer.nvim-ufo")
require("packer.dap")
require("packer.leap")
require("lsp-file-operations").setup()
-- require("mason-nvim-lint").setup()
